---
title: "BNE Posterior Draws Output examine (in progress)"
author: "Robbie M. Parks"
date: '2023-08-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

Load pacakges
```{r}
library(ggplot2)
library(here)
library(nimble)
library(tidyverse)
```

Load processed posterior air pollution PM2.5 data
```{r}
dat_output_total_final <- data.frame()
for (year_selected in c(2010:2015)) {
  dat_output_total <- readRDS(paste0(here::here(), "/data/Washington/", year_selected, "_53_ZCTA_500_draws.rds"))
  dat_output_total_final <- data.table::rbindlist(list(dat_output_total_final, dat_output_total))
}
```

Calculate SD per ZCTA
```{r}
zcta_long <- dat_output_total_final %>%
  pivot_longer(cols = -c(year, zcta)) %>%
  group_by(year, zcta) %>%
  mutate(zcta = as.numeric(as.character(zcta)))
```

Seattle ZCTAs
```{r}
zcta_seattle <- c(
  98101, 98102, 98103, 98104, 98105,
  98106, 98107, 98108, 98109, 98112,
  98115, 98116, 98117, 98118, 98119,
  98121, 98122, 98125, 98126, 98133,
  98134, 98136, 98144, 98146, 98154,
  98164, 98174, 98177, 98178, 98195,
  98199
)
```

Plot histogram of 1 year per ZCTA in Seattle
```{r}
ggplot(data = zcta_long %>% filter(year == 2010) %>% filter(zcta %in% zcta_seattle)) +
  geom_histogram(aes(x = value)) +
  facet_wrap(~zcta)
```

Load ZCTA Washington shapefile from https://www2.census.gov/geo/tiger/TIGER2010/ZCTA5/2010/?C=D;O=A
```{r}
# state_shapefile = rgdal::readOGR(dsn=paste0(here::here(),'/data/shapefiles/zcta/tl_2010_',state_selected,'_zcta510'), layer=paste0('tl_2010_',state_selected,'_zcta510'))
#
# # prepare ZCTA column for merging later
# state_shapefile$ZCTA5CE10 = as.integer(state_shapefile$ZCTA5CE10)
#
# # reproject shapefile
# state_shapefile = spTransform(state_shapefile, CRS("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"))
#
# # fortify to prepare for plotting in ggplot
# map = fortify(state_shapefile)
#
# # extract data from shapefile
# state_shapefile@data$id = rownames(state_shapefile@data)
# shapefile.data = state_shapefile@data
#
# # merge selected data to map_create dataframe for colouring of ggplot
# shapefile.df = merge(map, shapefile.data, by='id')
```
